### ISSUE TITLE
support for whatsapp beta

### ISSUE THREAD

**Issue by tfsomrat** [diospiroverde/WazzApp#10]
Hey @diospiroverde 

This is the most functional WhatsApp client I have ever used in ubuntu. Thanks for making this. but I want to let you know that, web.whatsapp.com now supports WhatsApp beta (which allows us to use multi-device login). and pretty much every other WhatsApp client support that, except this one. can you add this support? it will be great then.

**Comment by diospiroverde** [comment]
Hi, tfsormat.

WazzApp 0.2.3 is now compatible with WhatsApp Beta.

if you installed it via snap store, just run snap refresh wazzapp in the command line.

All the best.

**Comment by tfsomrat** [comment]
It's working 🔥. Thanks a lot ❤️
