### ISSUE TITLE
Please update it to Chrome 60+

### ISSUE THREAD

**Issue by somratpro** [diospiroverde/WazzApp#12]
It's very annoying, sometimes I am chatting on it, and then suddenly appears a page that told me to update chrome version 60+

when I closed and re-open it, then it works again. I did clear the session cache.  but still, sometimes it appears. can you please update the chrome engine? thank you.

**Comment by diospiroverde** [comment]
Is it still happening with version 0.3.1?

**Comment by diospiroverde** [comment]
If you've installed via snap, please run 

snap refresh wazzapp

to ensure you have the latest version.

**Comment by somratpro** [comment]
Yes, It's still happening with 0.3.1, and I am using this version 😑

**Comment by diospiroverde** [comment]
Try this...

snap remove --purge wazzapp
snap install wazzapp

Alternatively you may use the .deb package or AppImage, that should have no problems with versions.

After the latest updates I stopped experiencing this problem, I think the --purge option may help.

Please let me know how it went.

**Comment by somratpro** [comment]
I told you that I am using the latest version. and suddenly it's logged out me today, and I can't even logging in back.

**Comment by diospiroverde** [comment]
Latest version is 0.3.3, are you sure you have it installed?

**Comment by somratpro** [comment]
![image](https://user-images.githubusercontent.com/37659754/141336648-c2a99722-2983-4b06-8518-168c838c1487.png)

**Comment by diospiroverde** [comment]
Can you try the .deb version to see if the problem remains?

**Comment by somratpro** [comment]
It's working now, thank you. hope it will work smoothly all the time.
