### ISSUE TITLE
Could you please add again minimize button?

### ISSUE THREAD

**Issue by gabmen1711** [diospiroverde/WazzApp#13]
Last update removed the minimize button, maybe there's a way to enable it, but I don't see it.

Could you please re add it or add an option to enable it?

![ScreenShotWazzApp](https://user-images.githubusercontent.com/15097990/141792216-798697fb-18fb-4a86-bd5b-80e5fb82a230.png)

**Comment by diospiroverde** [comment]
Hi, this is strange, I have the minimize button as normal in my computer. I'll check this issue later today and get back to you.

Can you tell me what's your Linux Distro?

All the best.

**Comment by gabmen1711** [comment]
Hello!

Thanks for the reply, I updated to latest version due to the Chrome update last week and since that moment the minimize button disappeared, I am using Ubuntu 20.04 

![image](https://user-images.githubusercontent.com/15097990/141801687-d642fad6-d040-43c2-959f-eced7a32ede0.png)

**Comment by diospiroverde** [comment]
I'm going to ask you to try two things.

If you installed via snap, please run

snap remove --purge wazzapp
snap install wazzapp

(this will completely reinstall the wazzapp snap).

If this doesn't work, can you install the .deb version to see if you get the minimize button?

https://lx-dynamics.com/wazzapp_0.3.8_amd64.deb

I'll try a VM with your OS version to see if I can reproduce the problem.

**Comment by gabmen1711** [comment]
Option 1 actually fixed it, removed with purge and installed again.

Thank you very much for your help.

I will close the issue now, as it is all working perfectly now!
