### ISSUE TITLE
Font Missing Issue

### ISSUE THREAD

**Issue by somratpro** [diospiroverde/WazzApp#14]
Hey man, how are you?
Just got an issue that the system font is missing. 
![whatsapp](https://user-images.githubusercontent.com/37659754/155325545-c5bd5c4a-5c67-4982-9d93-0d7e49e047bb.png)
![whatsapp-about](https://user-images.githubusercontent.com/37659754/155325680-76f57919-0da2-45fc-9583-652258723e7d.png)

**Comment by diospiroverde** [comment]
Hi, somratpro.

Hope you are well.

This sometimes happens with snap apps. Can you please try the following procedure to regenerate the font cache?

`rm -rf ~/.cache/fontconfig 
sudo fc-cache -r -v`

If this isn't enough, please try this...

`rm -rf ~/.cache/fontconfig 
sudo fc-cache -r -v`

**Comment by diospiroverde** [comment]
Can you please try this and the restart the app?

`sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r`

**Comment by somratpro** [comment]
The output doesn't looks good
`zsh: no matches found: /var/cache/fontconfig/*`

**Comment by somratpro** [comment]
Just did, But the issue doesn't resolve. I don't know what's wrong with it, very frustrating 😑

**Comment by diospiroverde** [comment]
You can also do this...

`find ~/snap/wazzapp/ -name 'fontconfig'`

and delete every fontconfig folder it finds.

then

`sudo fc-cache -r`

If this doesn't work I'll take a better look into it when I get home.

Can you please tell me your OS version?

**Comment by diospiroverde** [comment]
If you need a quick solution you may try installing the app image from https://lx-dynamics.com/wazzapp-0.3.9.AppImage

**Comment by diospiroverde** [comment]
I have published a new version that *should* solve the issue with Manjaro (this distro seems to be having problems with snapcraft and fonts).

If you want to keep using the snap version please run

`snap remove --purge wazzapp`

and then

`snap install wazzapp`

and please let me know if it worked. I had to manually patch electron-builder to make it use core20 as base, it's not yet supported by default.

**Comment by somratpro** [comment]
I am sorry to say that, it doesn't work. It's updated to 0.4.1 version. but the issue is the same. maybe it's my pc problem. You are a really good developer. I appreciate you bro ❤️

**Comment by diospiroverde** [comment]
Thank you very much bro. 

I will install a virtual machine with your distro to see if it works on my side and get back to you as soon as I can.

**Comment by diospiroverde** [comment]
Hi,

I've installed a VM with Manjaro-Gnome and I was able to reproduce part of the problem. When clicking the about box all I could see was squares.

This is caused by a bug with fontconfig that's been affecting a lot of snaps in fedora and arch base distros like Manjaro.

I used this workaround to get the fonts to display correctly.

`rm -r /snap/wazzapp/common/.cache/fontconfig
touch ~/snap/wazzapp/common/.chage/fontconfig`

This will have the drawback of making the dialog box take a few seconds to display the first time you click it.

I seriously recommend using the AppImage with arch based distros until this issue with fontconfig gets solved, but if you do try the above workaround please let me know if it worked.

**Comment by somratpro** [comment]
Sorry bro, It's not worked. But I still want to use it, because I can't permanently install AppImage, It runs, and when I close it. It needs to sign in again, which is inconvenient.

**Comment by diospiroverde** [comment]
I made a package specifically for your system, this should sort things out.

You can download it from [https://lx-dynamics.com/wazzapp-0.3.9-1-x86_64.pkg.tar.zst](url)

and install it with

`sudo pacman -U wazzapp-0.3.9-1-x86_64.pkg.tar.zst`

**Comment by somratpro** [comment]
I think it's working. You are a magician bro, just love your work. 🥳
