### ISSUE TITLE
Auto launch Wazzapp Snap Debian 11 XFC3

### ISSUE THREAD

**Issue by fleamour** [diospiroverde/WazzApp#5]
What is the syntax to launch Wazzapp snap from terminal?

**Comment by diospiroverde** [comment]
You should only have to write wazzapp (all lowercase) in the command line.

Please let me know if it worked.

**Comment by fleamour** [comment]
This does not work via bash or fish.

**Comment by diospiroverde** [comment]
Hi, can you please try with /snap/wazzapp/current/wazzapp ?

**Comment by fleamour** [comment]
That right on tha monay!
