### ISSUE TITLE
Access to media and partitions disabled

### ISSUE THREAD

**Issue by franciscodara** [diospiroverde/WazzApp#6]
Access media and partition mount points, please!

![image](https://user-images.githubusercontent.com/29130959/131927464-31e4c700-5e07-4398-8196-aa417337241a.png)

**Comment by diospiroverde** [comment]
Hi,

Sorry for the late response.

I'll address this and get back to you.

**Comment by diospiroverde** [comment]
Hi,

Access to media partitions is now possible with version 0.2.5.

Just run in the command line the following commands...

sudo snap refresh wazzapp 
(this is to update to the latest version).

sudo snap connect wazzapp:removable-media 
(this is to enable access to removable media).
