### ISSUE TITLE
New Feature: disable keyboard shortcuts

### ISSUE THREAD

**Issue by serhumanos** [diospiroverde/WazzApp#7]
Hi, I like to suggest a new feature: disable keyboard shortcuts.
I think it will be a good option to prevent mark all messages as read or archived, etc accidentally
greetings!

**Comment by diospiroverde** [comment]
Hi serhumanos,

Thank you, I will implement it in the next release along with some other updates.

All the best.

**Comment by serhumanos** [comment]
Cool! Thank you!

**Comment by diospiroverde** [comment]
Hi,

This has been implemented in the latest release.

All the best.

**Comment by serhumanos** [comment]
Hi! I am using the Wazzapp 0.2.8 and this option do not work, if I disable shortcuts, and restart de app, the shortcuts keep working

Anyone has this problem too? or only me?
thanks

**Comment by diospiroverde** [comment]
Hi.,

I will check this today and let you know.

**Comment by diospiroverde** [comment]
Hi,

This seems to be working OK on my side, can you please run

snap refresh wazzapp

to update to version 0.3.0 and check if the problem remains?

All the best.

**Comment by diospiroverde** [comment]
Please don't forget to close wazzapp and reopen it for the changes to take effect.

**Comment by serhumanos** [comment]
I recently installed the new version 0.3.1 (i'm using .deb installer, not snap)
"disable shortcuts" option is not working for me, if I disabled it, the showed indicator shortcuts "Ctrl+R", "Ctrl+S" still showing and working

could be that I am using de .deb version?

**Comment by diospiroverde** [comment]
It's possible, I'll check the .deb version and let you know.

**Comment by diospiroverde** [comment]
I installed the .deb in my machine and the feature is working normally. I wonder if the setting is getting saved. If you go to the settings menu is the option "disable shortcuts" ticked?

Can you tell me what's your linux distro?

It has to be like in the following image

![image](https://user-images.githubusercontent.com/79201496/141190556-8cf5bd34-e332-416c-82a0-474e1786db8c.png)

**Comment by serhumanos** [comment]
yes, the setting is saved, and keep it the same state after reboot app

![image](https://user-images.githubusercontent.com/7744939/141204738-d7cee032-68b1-4b12-bfcc-8d4c9461fc17.png)

OS: KDE Neon 5.23 User Edition (Ubuntu 20.04 Based)

**Comment by diospiroverde** [comment]
I'll be installing this in a Virtual Machine with Kubuntu and let you know if I can reproduce the problem. In case I can't reproduce it on my side, I'll make some changes to try to double check that the keyboard accelerators are off and ask you to test it.

**Comment by serhumanos** [comment]
> I'll be installing this in a Virtual Machine with Kubuntu and let you know if I can reproduce the problem. In case I can't reproduce it on my side, I'll make some changes to try to double check that the keyboard accelerators are off and ask you to test it.

this is the download iso for KDE NEON https://neon.kde.org/download
I think that kubuntu may be work too

**Comment by diospiroverde** [comment]
Thank you, I'm going to download that disto now.

**Comment by diospiroverde** [comment]
I installed that ISO and ran wazzapp via .deb and it worked ok on my virtual machine.

Could you do me the favor of uninstalling your wazzapp deb and install this one?

https://lx-dynamics.com/wazzapp_0.3.3_amd64_dev.deb

This is a small development version that I complied just to make sure the problem still remains. If that's the case I'll send you a version with further checks to ensure the keyboard shortcuts are turned off.

**Comment by diospiroverde** [comment]
Hi, I can now see this has  been a huge misunderstanding.

The disable shortcuts option was only designed to turn off the Mark all as read, Mark all as unread and the Archive all keyboard shortcuts. This was entirely my fault, I should have named the option in a clearer way. 

I now understand you want to turn off the settings and the reload options.

I will implement an option to disable ALL shortcuts  in the next version. Sorry for the misunderstanding.

I'll let you know when a new version is available.

**Comment by diospiroverde** [comment]
Hi,

You can now install version 0.3.5 and the option will now disable ALL shortcuts.

Again, sorry for the misunderstanding, you had clearly stated which shortcuts were still functioning, but I didn't read it properly.

All the best.
